### ISSUE TITLE
EPIC: F1 - Frontend changes to UsersTable (PRIORITY)

### ISSUE THREAD

**Issue by bella-ward** [ucsb-cs156-f23/proj-organic-f23-6pm-3#7]
This is a priority issue worth at least 20 points.  You may be able to  earn more if you break it into multiple issues/PRs.

# User Story

* As an admin
* I can change the roles of other users, granting/revoking admin and instructor status
* So that I can designate any user for any role

### Discussion

In the code base for proj-gauchoride, there is functionality that allows admins to designate any user as any combination of admin, driver, and rider.

We want to add similar functionality to this app, though we only need to concern ourselves with two roles for the time being: admin, and instructor.

You can reuse a lot of the code that you find in the proj-gauchoride code base for these features (see <https://github.com/ucsb-cs156/proj-gauchoride>).

# This is an Epic, not a single issue

This is an Epic, meaning that this issue is intended to be the "master issue" that is broken into multiple individual issues.

Copy the user stories/acceptance criteria into a separate  issue before starting to work on it, and make PRs for each part separately.  Benefits to this staged approach:
* You'll earn more points that way
* You'll earn them more quickly
* PRs are easier to code review and merge
* If you don't finish, you get partial credit for what you did complete, and students in a future class can finish off your work.

### Acceptance Criteria

This is a priority issue worth at least 20 points: 10 for the frontend, and 10 for the backend.

This epic is broken into one backend issue, and one frontend issue.  You are encouraged to complete them separately, and possibly even break this into smaller issues if needed.

<img width="316" alt="image" src="https://github.com/ucsb-cs156/proj-organic/assets/1119017/8edecd93-43e8-4439-ae46-0f8c187e9d09">

# Issue F1: Frontend changes to UsersTable 

- [x] Add the `instructor` column to the UsersTable component next to the `admin` column.
- [x] The UsersTable (currently used on `AdminUsersPage` and the `ProfilePage` has a new property `showToggleButtons` that defaults to false
- [x] When the showButtons property is true, the UsersTable component includes buttons to toggle admin and instructor status, similar to the buttons on the [UsersTable from proj-gauchoride](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/frontend/src/main/components/Users/UsersTable.js)
- [x] A storybook story for UsersTable is added with two entries: one that shows the table without the buttons, and another with the buttons. ([This file](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/frontend/src/stories/components/Users/UsersTable.stories.js) may be helpful as an example.)
- [ ] The value of showToggleButtons on the AdminUsersPage is set to true, and the buttons there actually toggle the statuses.  
- [ ] Status changes are reflected both in the admin users table and on the actual users logged in session.

### Implementation Todos

You are encouraged to play with a deployment of proj-gauchoride to get a sense of how this feature works when it works properly, and compare your code with that code as you deploy.
